name: "Build clean GKI kernel"

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: 'Tên Kernel của bạn (Ví dụ: -CleanGKI)'
        required: true
        type: string
        default: '-CleanGKI'

      kernel_repo:
        description: 'Kernel source repository'
        required: true
        type: string
        default: 'Pzqqt/android_kernel_xiaomi_marble'

      kernel_branch:
        description: 'Kernel source branch, tag, or commit'
        required: true
        type: string
        default: 'melt-rebase'

      enable_ccache:
        description: 'Enable ccache'
        required: false
        type: boolean
        default: true

env:
  OUT_DIR: "out"
  ARCH: "arm64"
  DEFCONFIG_NAME: "vendor/marble_defconfig" 

jobs:
  Build-Kernel:
    name: "Build clean kernel"
    runs-on: ubuntu-22.04 
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev python3 python-is-python3 libarchive-tools ccache

      - name: "Clone Toolchain (Proton Clang)"
        run: |
          echo "Downloading Proton Clang Toolchain..."
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchain
          
      - name: "Clone kernel source"
        run: |
          echo "Downloading Kernel Source..."
          KERNEL_REPO="https://github.com/${{ github.event.inputs.kernel_repo }}.git"
          KERNEL_BRANCH="${{ github.event.inputs.kernel_branch }}"
          
          git clone --depth=1 -b "$KERNEL_BRANCH" "$KERNEL_REPO" android-kernel

      - name: "Make defconfig"
        working-directory: ./android-kernel
        run: |
          export PATH="${GITHUB_WORKSPACE}/toolchain/bin:${PATH}"
          make -j$(nproc --all) O=${{ env.OUT_DIR }} ARCH=${{ env.ARCH }} LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CC=clang ${{ env.DEFCONFIG_NAME }}

      - name: "Build kernel"
        working-directory: ./android-kernel
        run: |
          export PATH="${GITHUB_WORKSPACE}/toolchain/bin:${PATH}"
          
          if [ "${{ github.event.inputs.enable_ccache }}" == "true" ]; then
            CCACHE="ccache"
          else
            CCACHE=""
          fi
          
          make -j$(nproc --all) O=${{ env.OUT_DIR }} ARCH=${{ env.ARCH }} LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CC="$CCACHE clang" LOCALVERSION="${{ github.event.inputs.kernel_name }}"

      - name: "Upload Image"
        uses: actions/upload-artifact@v4
        with:
          name: Image${{ github.event.inputs.kernel_name }}
          path: ./android-kernel/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image
          if-no-files-found: ignore
          retention-days: 7

      - name: "Upload dtb"
        uses: actions/upload-artifact@v4
        with:
          name: dtb${{ github.event.inputs.kernel_name }}
          path: ./android-kernel/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dts/**/*.dtb
          if-no-files-found: ignore
          retention-days: 7
          
